# Generated by Buildr 1.4.4, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "bank"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

ejb_layout = Layout.new
ejb_layout[:source, :main, :java] = 'src'

web_layout = Layout.new
web_layout[:source, :main, :java] = 'src'
web_layout[:source, :main, :webapp] = 'WebContent'

Project.local_task(:deploy) {|name| "Deploying project #{name}"}
Project.local_task(:undeploy) {|name| "Undeploying project #{name}"}
Project.local_task(:create_db) {|name| "Creating database for #{name}"}
Project.local_task(:populate_db) {|name| "Populating database for #{name}"}

JBOSS_DIR = '../jboss-4.0.5.GA/server/default/deploy/'

desc "The Bank project"
define "bank" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "BankEar" do
    package(:ear).add :jar=>project('AppClient'), :path=>''
    package(:ear).add :ejb=>project('BankEjb'), :path=>''
    package(:ear).add :war=>project('BankWeb'), :path=>'', :context_root=>'bank'
    package(:ear).include(path_to('conf/*'), :path=>'')
    package(:ear).display_name = 'JBossDukesBank'
    package(:ear).security_roles << {:name=>'BankAdmin', :id=>"admin", :description=>"Administrator role"}
    package(:ear).security_roles << {:name=>'BankCustomer', :id=>"customer", :description=>"Customer role"}
  end

  define "AppClient", :layout=>ejb_layout do
    compile.with project('BankEjb'), project('BankEjb').compile.dependencies
    package(:jar).include path_to(:source, :main, :java, '/**/*properties'), :path=>'appclient'
  end

  define "BankEjb", :layout=>ejb_layout do
    compile.with Dir[path_to('lib/*.jar')]
    package(:jar)
  end

  define "BankWeb", :layout=>web_layout do
    compile.with project('BankEjb'), project('BankEjb').compile.dependencies
    package(:war).include path_to(:source, :main, :java, '/**/*properties'), :path=>'WEB-INF/classes'
    package(:war).with :libs=>path_to(:source, :main, :webapp, 'WEB-INF/lib/*')
  end

  task :deploy => :package do
    cp project('BankEar').package(:ear).to_s, JBOSS_DIR  
  end

  task :undeploy do
    rm File.join(JBOSS_DIR, project('BankEar').package(:ear).name.split('/').last)
  end

  task :create_db do
    run_hsql_script('sql/hsql-create-table.sql')
  end

  task :populate_db do
    run_hsql_script('sql/hsql-insert.sql')
  end

  def run_hsql_script(script)
    system "java -cp sql/hsqldb.jar org.hsqldb.util.ScriptTool -url jdbc:hsqldb:hsql: -database //localhost:1701 -script #{script}"
  end
  
end


